export { App, type AppServices } from "./App";
export { type CounterService, WatchCounter } from "./components/WatchCounter";
export { DashboardPage } from "./pages/Dashboard";
export { MarkdownReaderPage, type FileSystemService } from "./pages/MarkdownReader";
export { SettingsPage, type SettingsService } from "./pages/Settings";
export { TerminalPage, type TerminalService } from "./pages/Terminal";
export { Sidebar } from "./layouts/Sidebar";
export { type NavItem } from "@watchdesk/contracts";
export { type Page } from "@watchdesk/contracts";
export { WatchDeskLayout } from "./layouts/WatchDeskLayout";
export { useTerminalView, TerminalViewCtx } from "./context/terminal-view.context";
